configuration:
  swagger:
    app: "Finance Management System"
    description: "A simple system built with Spring Boot"
    developer: "Emir Kugic"
    email: "emir.kugic@ibu.edu.ba"

mailsender:
  default: "sendgrid"

security:
  jwt:
    secret: "mXLjT3Gm4skNsCdntWodbHPb1GqY35fGVaisLwImIp8cLZP7W6"

#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: finance_tracker

spring:
  data:
    mongodb:
      uri: mongodb+srv://emirkugic:emirkugic@web.dansdge.mongodb.net/?retryWrites=true&w=majority
      database: finance_tracker
# imgur:
#   client:
#     id: "ab0ad10e479e687"
